[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_NEXTAUTH_URL = "https://your-app-name.netlify.app"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs" 